### ISSUE TITLE
Support for nvenc codec

### ISSUE THREAD

**Issue by baseplate-admin** [DreamOfIce/ffmpeg.wasm#3]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
I want `ffmpeg.wasm` to support [`nvenc`](https://en.wikipedia.org/wiki/Nvidia_NVENC) encoding.

**Describe alternatives you've considered**
Not use `ffmpeg.wasm` at all.

**Additional context**
Hi, thanks for maintaining this awesome package. 

I am genuinely impressed that such a complex piece of software can be ported to `wasm` like this.

Back to my point, can we please support `nvenc` encoder for `ffmpeg.wasm`? 

As it turns out [nvidia provides an awesome guide on how to add `nvenc` support to `ffmpeg`](https://docs.nvidia.com/video-technologies/video-codec-sdk/11.1/ffmpeg-with-nvidia-gpu/index.html).

This feature was also [requested on mainline `ffmpeg.wasm` ](https://github.com/ffmpegwasm/ffmpeg.wasm/issues/61#issuecomment-729312113)( but as we all are aware the project is lacking a bit of maintenance ).

Thanks a bunch

**Comment by DreamOfIce** [comment]
Currently wasm does not seem to have the ability to call nvenc and other gpu codecs
