### ISSUE TITLE
Property 'writeFile' does not exist on type 'FFmpegFileSystem'

### ISSUE THREAD

**Issue by Xhale1** [DreamOfIce/ffmpeg.wasm#5]
**Describe the bug**
ffmpeg.fs.writeFile throws the error `Property 'writeFile' does not exist on type 'FFmpegFileSystem'`.

**To Reproduce**
Follow the readme here https://github.com/FFmpeg-wasm/FFmpeg.wasm#usage

**Expected behavior**
ffmpeg.fs.writeFile is documented by typescript

**Desktop (please complete the following information):**

- OS: [e.g. iOS] MacOS
- Browser [e.g. chrome, safari] N/A
- Version [e.g. 22] 13.5

**Additional context**
Running latest version of VSCode.

**Comment by DreamOfIce** [comment]
Can you run `pnpm test --run` in the ffmpeg.wasm repo and paste the output?

**Comment by DreamOfIce** [comment]
Sorry, I seem to have misunderstood. You mean there is an error in Typescript declaration right?

**Comment by DreamOfIce** [comment]
Could you try to add `@types/emscripten` to the devDependencies and see if the problem still exists?

I'm still working on a simpler way.

**Comment by teetow** [comment]
Not OP, but adding `@types/emscripten` worked for me.

**Comment by wesbos** [comment]
Same issue here, before installing @types/emscripten, I only saw these methods:

mount
mkdir
mkdev
symlink
readdir
stat
lstat
llseek

After installing I see all emscripten methods. I think your types need to be updated

**Comment by DreamOfIce** [comment]
> Same issue here, before installing @types/emscripten, I only saw these methods:

Because we override the type signatures of these methods
This will be fixed in a new version released recently.

**Comment by DreamOfIce** [comment]
@wesbos @teetow @Xhale1 This problem should be fixed in v0.13.1
